allowBuilds:
  '@alicloud/openapi-core': set this to true or false
  esbuild: true
  sharp: true
  workerd: true
injectWorkspacePackages: true
overrides:
  fast-uri@3: 3.1.5
packages:
  - "."
  - "apps/*"
  - "packages/*"

syncInjectedDepsAfterScripts:
  - build

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
